//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose opponent-&gt;.
        /// </summary>
        public static string ChooseOpponent {
            get {
                return ResourceManager.GetString("ChooseOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to proceed.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm window.
        /// </summary>
        public static string ConfirmWindow {
            get {
                return ResourceManager.GetString("ConfirmWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal difference:.
        /// </summary>
        public static string GoalDifference {
            get {
                return ResourceManager.GetString("GoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals given:.
        /// </summary>
        public static string GoalsGiven {
            get {
                return ResourceManager.GetString("GoalsGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals received:.
        /// </summary>
        public static string GoalsReceived {
            get {
                return ResourceManager.GetString("GoalsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect.
        /// </summary>
        public static string Inspect {
            get {
                return ResourceManager.GetString("Inspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window.
        /// </summary>
        public static string MainWindow {
            get {
                return ResourceManager.GetString("MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player details.
        /// </summary>
        public static string PlayerStatsWindow {
            get {
                return ResourceManager.GetString("PlayerStatsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings window.
        /// </summary>
        public static string SettingsWindow {
            get {
                return ResourceManager.GetString("SettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team 1 starting 11.
        /// </summary>
        public static string Team1Starting {
            get {
                return ResourceManager.GetString("Team1Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team 1 substitutions.
        /// </summary>
        public static string Team1Subs {
            get {
                return ResourceManager.GetString("Team1Subs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team 2 starting 11.
        /// </summary>
        public static string Team2Starting {
            get {
                return ResourceManager.GetString("Team2Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team 2 substitutions.
        /// </summary>
        public static string Team2Subs {
            get {
                return ResourceManager.GetString("Team2Subs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of games played:.
        /// </summary>
        public static string TeamGamesPlayed {
            get {
                return ResourceManager.GetString("TeamGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games lost:.
        /// </summary>
        public static string TeamLosses {
            get {
                return ResourceManager.GetString("TeamLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team details.
        /// </summary>
        public static string TeamStatsWindow {
            get {
                return ResourceManager.GetString("TeamStatsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games undecided:.
        /// </summary>
        public static string TeamUndecided {
            get {
                return ResourceManager.GetString("TeamUndecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games won:.
        /// </summary>
        public static string TeamWins {
            get {
                return ResourceManager.GetString("TeamWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards received:.
        /// </summary>
        public static string YellowCards {
            get {
                return ResourceManager.GetString("YellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
